[package]
name = "w_analyze"
version = "0.1.0"
edition = "2021"

[dependencies]
w_parse = { path = "../w_parse" }
w_tokenize = { path = "../w_tokenize" }
w_rcstr = { path = "../w_rcstr" }

assert_matches = "1.5.0"
typed-arena = "2.0.1"
either = "1.8.0"
uuid = "1.1.2"
ariadne = "0.1.5"
